# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ['3.7']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install pip dependency
      run: pip install tox codecov
    - name: Script
      run: |
        # Add conditional check to skip the step
        if [ "${{ matrix.os }}" != "macos-latest" ] || [ "${{ matrix.python-version }}" != "3.7" ]; then
          tox -e py
        else
          echo "Skipping Script step for macOS-latest with Python 3.7"
        fi
      shell: bash
    - name: After Success
      run: codecov
